### ISSUE TITLE
Amplitudes consistent with previous Allen datasets

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-units-nwb#2]
As far as I can tell, unit amplitudes are currently taken as the voltage at a particular index in the waveform:
https://github.com/SpikeInterface/spikeinterface/blob/024c24afaec2d0a0476017c77a75f7c8a1dcb4b3/src/spikeinterface/core/template_tools.py#L108-L109

..whereas former MindScope datasets used pk-pk amplitude.

I've been overwriting the `amplitude` column with pk-pk values, which is what we want for Dynamic Routing NWBs (@corbennett, @egmcbride). I think @jsiegle might be doing the same. 

Do you think we could agree on the amplitude we want to use and just store that in the NWB generated here?

**Comment by jsiegle** [comment]
I agree this should be using `peak_sign = both` and `mode = extremum` to be consistent with previous conventions.

**Comment by alejoe91** [comment]
This has been fixed with `mode="peak_to_peak"`
