### ISSUE TITLE
`isi_violations_ratio` incorrect name

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-units-nwb#3]
Since moving to the pipeline sorting with NWB packaging, there are some discrepancies between the values in NWB.units and `postprocessed/quality_metrics.csv`, and some errors. 
I'll likely submit individual issues for each as I find them.

- `quality_metrics.csv` contains `isi_violations_count` and `isi_violations_ratio`
- `NWB.units` only contains `isi_violations_ratio`, but the values look like `isi_violations_count`

![image](https://github.com/AllenNeuralDynamics/NWB_Packaging_Units/assets/63425812/e9742fc8-e373-47bc-8fc5-658ad03d0c01)

**Comment by alejoe91** [comment]
Thanks for the report Ben. Add you check individual values in the CSV and nwb file or just visualized the histogram?

**Comment by bjhardcastle** [comment]
It looks like ratio and count are similar to each other in the csv:
![image](https://github.com/AllenNeuralDynamics/NWB_Packaging_Units/assets/63425812/f8cbbcdf-21a7-49e5-9528-96963794578a)

**Comment by alejoe91** [comment]
They are super correlated. Can you plot a scatter plot? Ratios should have many more values between 0 and 1, but they can also be greater than 1 for high contamination

**Comment by bjhardcastle** [comment]
Right ok, and it looks like both are in the NWB after all, it's just the figurl summary that was not showing count.

![image](https://github.com/AllenNeuralDynamics/NWB_Packaging_Units/assets/63425812/9fecab33-9421-47f8-b9ed-47ead2002f8d)

**Comment by bjhardcastle** [comment]
So all is fine - thanks for your help!
